import {useEffect,useState} from 'react';
import {ActivityIndicator,Modal,Pressable,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import type {Notebook} from '../types';
import {downloadCloudBackup,emptyCloudConfig,listCloudBackups,loadCloudConfig,saveCloudConfig,testCloudConnection,uploadArchiveIfEnabled,type CloudBackup,type CloudConfig} from '../cloudSync';
import {importLibraryBackupFromUri,writeAutomaticBackup} from '../backup';
import {C} from '../theme';

export function CloudSyncPanel({visible,onClose,items,onRestore}:{visible:boolean;onClose:()=>void;items:Notebook[];onRestore:(items:Notebook[])=>void}){
 const [config,setConfig]=useState<CloudConfig>(emptyCloudConfig);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [backups,setBackups]=useState<CloudBackup[]>([]);
 useEffect(()=>{if(visible)void loadCloudConfig().then(setConfig)},[visible]);
 const run=async(action:()=>Promise<unknown>,success:string)=>{setBusy(true);setMessage('');try{await saveCloudConfig(config);await action();setMessage(success);if(config.endpoint&&config.token)setBackups(await listCloudBackups(config))}catch(error){setMessage(error instanceof Error?error.message:'작업 실패')}finally{setBusy(false)}};
 const sync=()=>run(async()=>{const uri=await writeAutomaticBackup(items,5,0);if(uri)await uploadArchiveIfEnabled(uri,{...config,enabled:true})},'R2 백업 완료');
 const restore=(backup:CloudBackup)=>run(async()=>{const uri=await downloadCloudBackup(config,backup);onRestore(await importLibraryBackupFromUri(uri))},`${backup.name} 복원 완료`);
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.scrim}><View style={s.card}><Text style={s.title}>Cloudflare R2 백업</Text><Text style={s.help}>Worker URL과 SYNC_TOKEN만 기기에 저장됩니다. R2 API 키는 앱에 들어가지 않습니다.</Text><TextInput value={config.endpoint} onChangeText={endpoint=>setConfig(x=>({...x,endpoint}))} autoCapitalize="none" placeholder="https://hanji-sync.example.workers.dev" style={s.input}/><TextInput value={config.token} onChangeText={token=>setConfig(x=>({...x,token}))} autoCapitalize="none" secureTextEntry placeholder="SYNC_TOKEN" style={s.input}/><View style={s.row}><Text style={s.label}>자동 클라우드 백업</Text><Switch value={config.enabled} onValueChange={enabled=>setConfig(x=>({...x,enabled}))}/></View>{message&&<Text style={s.message}>{message}</Text>}{backups.slice(0,5).map(x=><Pressable disabled={busy} onPress={()=>restore(x)} key={x.key} style={s.backupRow}><Text numberOfLines={1} style={s.backup}>• {x.name} · {(x.size/1024/1024).toFixed(1)}MB</Text><Text style={s.restore}>복원</Text></Pressable>)}{busy&&<ActivityIndicator color={C.accent}/>}<View style={s.actions}><Pressable onPress={onClose} style={s.secondary}><Text>닫기</Text></Pressable><Pressable disabled={busy} onPress={()=>run(()=>testCloudConnection(config),'연결 성공')} style={s.secondary}><Text>연결 테스트</Text></Pressable><Pressable disabled={busy} onPress={sync} style={s.primary}><Text style={{color:'white',fontWeight:'700'}}>지금 백업</Text></Pressable></View></View></View></Modal>
}
const s=StyleSheet.create({scrim:{flex:1,backgroundColor:'rgba(0,0,0,.35)',alignItems:'center',justifyContent:'center'},card:{width:520,maxWidth:'90%',backgroundColor:C.white,borderRadius:20,padding:22,gap:12},title:{fontSize:20,fontWeight:'800',color:C.ink},help:{fontSize:12,lineHeight:18,color:C.muted},input:{height:44,borderWidth:1,borderColor:C.line,borderRadius:11,paddingHorizontal:12,color:C.ink},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},label:{fontWeight:'700',color:C.ink},message:{color:C.accent,fontWeight:'700'},backupRow:{height:32,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.line},backup:{fontSize:11,color:C.muted,flex:1},restore:{fontSize:11,color:C.accent,fontWeight:'800'},actions:{flexDirection:'row',justifyContent:'flex-end',gap:8,marginTop:4},primary:{height:40,paddingHorizontal:14,borderRadius:10,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'},secondary:{height:40,paddingHorizontal:14,borderRadius:10,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'}});
