import {Ionicons} from '@expo/vector-icons';
import {useEffect,useMemo,useState} from 'react';
import {Image,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {createFlashcard,createImageFlashcard,dueFlashcards,reviewFlashcard,type ReviewGrade} from '../srs';
import {C} from '../theme';
import type {Flashcard} from '../types';

type Props={visible:boolean;cards:Flashcard[];initialQuestion?:string;initialQuestionImageUri?:string;onChange:(v:Flashcard[])=>void;onClose:()=>void};

export function FlashcardPanel({visible,cards,initialQuestion,initialQuestionImageUri,onChange,onClose}:Props){
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[questionImageUri,setQuestionImageUri]=useState<string>(),[reviewing,setReviewing]=useState(false),[revealed,setRevealed]=useState(false);
 useEffect(()=>{if(visible&&(initialQuestion||initialQuestionImageUri)){setQuestion(initialQuestion??'이미지 질문');setAnswer('');setQuestionImageUri(initialQuestionImageUri);setReviewing(false);setRevealed(false)}},[visible,initialQuestion,initialQuestionImageUri]);
 const due=useMemo(()=>dueFlashcards(cards),[cards]),current=due[0],canAdd=!!answer.trim()&&!!(question.trim()||questionImageUri);
 const add=()=>{if(!canAdd)return;const card=questionImageUri?createImageFlashcard(questionImageUri,question,answer):createFlashcard(question,answer);onChange([...cards,card]);setQuestion('');setAnswer('');setQuestionImageUri(undefined)};
 const grade=(g:ReviewGrade)=>{if(current)onChange(cards.map(c=>c.id===current.id?reviewFlashcard(c,g):c));setRevealed(false)};
 return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={s.root}>
  <View style={s.header}><View><Text style={s.eyebrow}>로컬 SM-2 학습</Text><Text style={s.title}>플래시카드</Text></View><Pressable accessibilityLabel="닫기" onPress={onClose} style={s.icon}><Ionicons name="close" size={24} color={C.ink}/></Pressable></View>
  {reviewing?<View style={s.review}>{current?<><Text style={s.progress}>학습 카드 {due.length}개</Text><Pressable onPress={()=>setRevealed(true)} style={s.card}><Text style={s.label}>질문</Text>{current.questionImageUri&&<Image source={{uri:current.questionImageUri}} resizeMode="contain" style={s.reviewImage}/>}<Text style={s.cardText}>{current.question}</Text>{revealed?<><View style={s.divider}/><Text style={s.label}>정답</Text><Text style={s.answer}>{current.answer}</Text></>:<Text style={s.hint}>탭해서 정답 보기</Text>}</Pressable>{revealed&&<View style={s.grades}>{([{g:0 as const,t:'다시',c:C.danger},{g:1 as const,t:'어려움',c:'#A66A32'},{g:2 as const,t:'보통',c:'#315E9C'},{g:3 as const,t:'쉬움',c:C.accent}]).map(x=><Pressable key={x.g} onPress={()=>grade(x.g)} style={[s.grade,{backgroundColor:x.c}]}><Text style={s.white}>{x.t}</Text></Pressable>)}</View>}</>:<><Ionicons name="checkmark-circle" size={54} color={C.accent}/><Text style={s.done}>오늘 복습 완료</Text><Text style={s.muted}>예정된 카드가 없습니다.</Text><Pressable onPress={()=>setReviewing(false)} style={s.primary}><Text style={s.white}>카드 관리</Text></Pressable></>}</View>:<><View style={s.summary}><View><Text style={s.count}>{due.length}</Text><Text style={s.muted}>오늘 복습</Text></View><View><Text style={s.count}>{cards.length}</Text><Text style={s.muted}>전체 카드</Text></View><Pressable disabled={!due.length} onPress={()=>setReviewing(true)} style={[s.primary,!due.length&&s.disabled]}><Text style={s.white}>복습 시작</Text></Pressable></View>
  <View style={s.form}><Text style={s.section}>새 카드</Text>{questionImageUri&&<View style={s.imageDraft}><Image source={{uri:questionImageUri}} resizeMode="contain" style={s.draftImage}/><Pressable accessibilityLabel="질문 이미지 제거" onPress={()=>setQuestionImageUri(undefined)} style={s.removeImage}><Ionicons name="close-circle" size={24} color={C.danger}/></Pressable></View>}<TextInput value={question} onChangeText={setQuestion} placeholder="질문" multiline style={s.input}/><TextInput value={answer} onChangeText={setAnswer} placeholder="정답" multiline style={[s.input,{minHeight:88}]}/><Pressable onPress={add} disabled={!canAdd} style={[s.primary,!canAdd&&s.disabled]}><Text style={s.white}>카드 추가</Text></Pressable></View>
  <ScrollView contentContainerStyle={s.list}>{cards.map(card=><View key={card.id} style={s.row}>{card.questionImageUri&&<Image source={{uri:card.questionImageUri}} style={s.thumbnail}/>}<View style={{flex:1}}><Text numberOfLines={1} style={s.question}>{card.question}</Text><Text style={s.meta}>다음 복습 {new Date(card.dueAt).toLocaleString('ko-KR')} · 간격 {card.intervalDays}일</Text></View><Pressable accessibilityLabel="카드 삭제" onPress={()=>onChange(cards.filter(x=>x.id!==card.id))} style={s.icon}><Ionicons name="trash-outline" size={18} color={C.danger}/></Pressable></View>)}</ScrollView></>}
 </View></Modal>;
}

const s=StyleSheet.create({root:{flex:1,backgroundColor:'#FBFAF7',padding:28},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:24},eyebrow:{fontSize:11,fontWeight:'700',color:C.accent,letterSpacing:1},title:{fontSize:28,fontWeight:'800',color:C.ink},icon:{width:40,height:40,alignItems:'center',justifyContent:'center'},summary:{flexDirection:'row',alignItems:'center',gap:34,padding:20,borderRadius:18,backgroundColor:C.accentSoft},count:{fontSize:26,fontWeight:'800',color:C.ink},muted:{color:C.muted,marginTop:3},primary:{backgroundColor:C.accent,minHeight:44,paddingHorizontal:20,borderRadius:12,alignItems:'center',justifyContent:'center',marginLeft:'auto',marginTop:12},white:{color:C.white,fontWeight:'800'},disabled:{opacity:.38},form:{gap:10,marginTop:24},section:{fontSize:16,fontWeight:'800',color:C.ink},input:{borderWidth:1,borderColor:C.line,borderRadius:12,backgroundColor:C.white,padding:13,minHeight:52,color:C.ink,textAlignVertical:'top'},list:{gap:8,paddingVertical:24},row:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:12,padding:13},question:{fontWeight:'700',color:C.ink},meta:{fontSize:11,color:C.muted,marginTop:5},review:{flex:1,alignItems:'center',justifyContent:'center'},progress:{fontSize:13,fontWeight:'700',color:C.muted,marginBottom:14},card:{width:'100%',maxWidth:680,minHeight:350,borderRadius:24,backgroundColor:C.white,borderWidth:1,borderColor:C.line,padding:34,justifyContent:'center'},label:{fontSize:11,fontWeight:'800',letterSpacing:1,color:C.accent},cardText:{fontSize:26,lineHeight:38,fontWeight:'800',color:C.ink,marginTop:12},answer:{fontSize:22,lineHeight:33,color:C.ink,marginTop:12},divider:{height:1,backgroundColor:C.line,marginVertical:28},hint:{position:'absolute',bottom:20,alignSelf:'center',color:C.muted,fontSize:12},grades:{flexDirection:'row',gap:10,marginTop:18,width:'100%',maxWidth:680},grade:{flex:1,height:48,borderRadius:12,alignItems:'center',justifyContent:'center'},done:{fontSize:24,fontWeight:'800',color:C.ink,marginTop:14},imageDraft:{height:180,borderRadius:14,backgroundColor:C.white,borderWidth:1,borderColor:C.line,overflow:'hidden'},draftImage:{width:'100%',height:'100%'},removeImage:{position:'absolute',right:8,top:8},reviewImage:{width:'100%',height:180,marginVertical:14},thumbnail:{width:56,height:42,borderRadius:6,backgroundColor:C.accentSoft}});
