import {Ionicons} from '@expo/vector-icons';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {folderBreadcrumb} from '../folders';
import {C} from '../theme';
import type {Notebook} from '../types';

export function PageTransferPanel({visible,sourceId,notebooks,onClose,onTransfer}:{visible:boolean;sourceId:string;notebooks:Notebook[];onClose:()=>void;onTransfer:(targetId:string,mode:'copy'|'move')=>void}){
 const targets=notebooks.filter(n=>n.id!==sourceId);
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={s.scrim} onPress={onClose}><Pressable style={s.card} onPress={()=>undefined}><View style={s.header}><View><Text style={s.eyebrow}>페이지 보내기</Text><Text style={s.title}>대상 노트 선택</Text></View><Pressable accessibilityLabel="닫기" onPress={onClose} style={s.close}><Ionicons name="close" size={22} color={C.ink}/></Pressable></View><Text style={s.help}>복사는 원본을 유지하고, 이동은 현재 노트에서 페이지를 제거합니다. 연결된 PDF·이미지·템플릿과 오디오 스트로크 참조도 함께 유지됩니다.</Text>{targets.length===0?<Text style={s.empty}>다른 노트를 먼저 만들어 주세요.</Text>:<ScrollView style={s.list}>{targets.map(note=><View key={note.id} style={s.row}><View style={s.note}><Ionicons name="document-text-outline" size={20} color={C.accent}/><View style={{flex:1}}><Text numberOfLines={1} style={s.noteTitle}>{note.title}</Text><Text numberOfLines={1} style={s.meta}>{folderBreadcrumb(note.folder)} · {note.pages.length}쪽</Text></View></View><Pressable accessibilityLabel={`${note.title}에 복사`} onPress={()=>onTransfer(note.id,'copy')} style={s.secondary}><Text style={s.secondaryText}>복사</Text></Pressable><Pressable accessibilityLabel={`${note.title}로 이동`} onPress={()=>onTransfer(note.id,'move')} style={s.primary}><Text style={s.primaryText}>이동</Text></Pressable></View>)}</ScrollView>}</Pressable></Pressable></Modal>;
}

const s=StyleSheet.create({scrim:{flex:1,backgroundColor:'rgba(25,27,24,.32)',alignItems:'center',justifyContent:'center',padding:24},card:{width:'100%',maxWidth:620,maxHeight:'78%',backgroundColor:C.white,borderRadius:22,padding:22},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1,color:C.accent},title:{fontSize:22,fontWeight:'800',color:C.ink,marginTop:3},close:{width:40,height:40,alignItems:'center',justifyContent:'center'},help:{fontSize:12,lineHeight:18,color:C.muted,marginTop:13,marginBottom:10},list:{marginTop:4},row:{minHeight:66,flexDirection:'row',alignItems:'center',gap:7,borderBottomWidth:1,borderBottomColor:C.line},note:{flex:1,flexDirection:'row',alignItems:'center',gap:10},noteTitle:{fontSize:14,fontWeight:'700',color:C.ink},meta:{fontSize:10,color:C.muted,marginTop:3},secondary:{height:36,paddingHorizontal:13,borderRadius:10,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:12,fontWeight:'700',color:C.accent},primary:{height:36,paddingHorizontal:13,borderRadius:10,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:12,fontWeight:'800',color:C.white},empty:{paddingVertical:40,textAlign:'center',color:C.muted}});
