import {Ionicons} from '@expo/vector-icons';
import {useEffect,useMemo,useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {DraggableGrid} from 'react-native-draggable-grid/built/src';
import {C} from '../theme';
import type {Page} from '../types';

type GridPage=Page&{key:string;order:number};
export function PageGridPanel({visible,pages,activeIndex,onClose,onSelect,onReorder,onDuplicate,onDelete,onBookmark,onTransfer}:{visible:boolean;pages:Page[];activeIndex:number;onClose:()=>void;onSelect:(index:number)=>void;onReorder:(ids:string[])=>void;onDuplicate:(id:string)=>void;onDelete:(id:string)=>void;onBookmark:(id:string)=>void;onTransfer:(id:string)=>void}){
 const [selectedId,setSelectedId]=useState<string>();useEffect(()=>{if(visible)setSelectedId(pages[activeIndex]?.id)},[visible,activeIndex,pages]);
 const data=useMemo<GridPage[]>(()=>pages.map((page,order)=>({...page,key:page.id,order})),[pages]);const selected=pages.find(p=>p.id===selectedId);
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.scrim}><View style={s.sheet}><View style={s.header}><View><Text style={s.eyebrow}>페이지 관리</Text><Text style={s.title}>{pages.length}개 페이지</Text></View><Text style={s.hint}>길게 누른 뒤 끌어서 재배열</Text><Pressable accessibilityLabel="페이지 관리 닫기" onPress={onClose} style={s.close}><Ionicons name="close" size={23} color={C.ink}/></Pressable></View><ScrollView contentContainerStyle={s.scroll}><DraggableGrid numColumns={4} itemHeight={150} data={data} onItemPress={item=>setSelectedId(item.id)} onDragRelease={items=>onReorder(items.map(item=>item.id))} renderItem={item=><View style={[s.cell,selectedId===item.id&&s.cellSelected]}><View style={[s.thumb,(item.rotation===90||item.rotation===270)&&s.thumbPortrait]}>{item.pdfUri&&<Ionicons name="document-outline" size={18} color={C.accent}/>} {!item.pdfUri&&<View style={s.lines}/>} {item.customTemplateUri&&<Ionicons name="layers" size={13} color={C.accent} style={s.layer}/>} {item.bookmarked&&<Ionicons name="bookmark" size={13} color="#B77A18" style={s.bookmark}/>}</View><Text style={s.pageNo}>{item.order+1}</Text></View>}/></ScrollView><View style={s.actions}><Text style={s.selectedText}>{selected?`${pages.findIndex(p=>p.id===selected.id)+1}페이지 선택됨`:'페이지를 선택하세요'}</Text><Pressable disabled={!selected} onPress={()=>selected&&onBookmark(selected.id)} style={s.action}><Ionicons name={selected?.bookmarked?'bookmark':'bookmark-outline'} size={18} color={C.accent}/><Text style={s.actionText}>북마크</Text></Pressable><Pressable disabled={!selected} onPress={()=>selected&&onDuplicate(selected.id)} style={s.action}><Ionicons name="copy-outline" size={18} color={C.accent}/><Text style={s.actionText}>복제</Text></Pressable><Pressable disabled={!selected} onPress={()=>selected&&onTransfer(selected.id)} style={s.action}><Ionicons name="git-compare-outline" size={18} color={C.accent}/><Text style={s.actionText}>보내기</Text></Pressable><Pressable disabled={!selected||pages.length===1} onPress={()=>selected&&onDelete(selected.id)} style={s.action}><Ionicons name="trash-outline" size={18} color={pages.length===1?C.line:C.danger}/><Text style={[s.actionText,{color:pages.length===1?C.line:C.danger}]}>삭제</Text></Pressable><Pressable disabled={!selected} onPress={()=>{if(!selected)return;onSelect(pages.findIndex(p=>p.id===selected.id));onClose()}} style={s.open}><Text style={s.openText}>열기</Text></Pressable></View></View></View></Modal>;
}

const s=StyleSheet.create({scrim:{flex:1,backgroundColor:'rgba(20,22,20,.35)',alignItems:'center',justifyContent:'center',padding:24},sheet:{width:'100%',maxWidth:760,height:'82%',backgroundColor:C.white,borderRadius:24,overflow:'hidden'},header:{height:76,flexDirection:'row',alignItems:'center',paddingHorizontal:24,borderBottomWidth:1,borderBottomColor:C.line},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1,color:C.accent},title:{fontSize:21,fontWeight:'800',color:C.ink,marginTop:2},hint:{marginLeft:'auto',fontSize:11,color:C.muted},close:{width:42,height:42,alignItems:'center',justifyContent:'center',marginLeft:10},scroll:{padding:18,paddingBottom:30},cell:{height:136,margin:6,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.sidebar,borderWidth:2,borderColor:'transparent'},cellSelected:{borderColor:C.accent,backgroundColor:C.accentSoft},thumb:{width:104,height:74,borderRadius:5,backgroundColor:C.paper,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',overflow:'hidden'},thumbPortrait:{width:54,height:78},lines:{width:'70%',height:'65%',borderTopWidth:1,borderBottomWidth:1,borderColor:'#DCE3DC'},layer:{position:'absolute',left:5,bottom:5},bookmark:{position:'absolute',right:5,top:0},pageNo:{fontSize:11,fontWeight:'800',color:C.muted,marginTop:7},actions:{height:68,borderTopWidth:1,borderTopColor:C.line,flexDirection:'row',alignItems:'center',paddingHorizontal:18,gap:7},selectedText:{fontSize:11,color:C.muted,marginRight:'auto'},action:{height:38,paddingHorizontal:10,borderRadius:10,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',gap:5},actionText:{fontSize:11,fontWeight:'700',color:C.accent},open:{height:40,paddingHorizontal:18,borderRadius:11,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'},openText:{color:C.white,fontWeight:'800'}});
