import {Ionicons} from '@expo/vector-icons';
import {Modal,Pressable,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {C} from '../theme';
import type {PageTemplate} from '../types';
import type {UiPreferences} from '../uiPreferences';

const templates:{value:PageTemplate;label:string}[]=[{value:'plain',label:'백지'},{value:'line',label:'줄'},{value:'grid',label:'격자'},{value:'dot',label:'점'},{value:'cornell',label:'코넬'},{value:'planner',label:'플래너'},{value:'dark',label:'다크'}];

export function SettingsPanel({visible,value,onChange,onClose}:{visible:boolean;value:UiPreferences;onChange:(value:UiPreferences)=>void;onClose:()=>void}){
 const toggle=(key:'leftHanded'|'fingerDrawingEnabled'|'autoDarkInk')=>(enabled:boolean)=>onChange({...value,[key]:enabled});
 return <Modal visible={visible} animationType="slide" presentationStyle="formSheet" onRequestClose={onClose}><View style={s.root}><View style={s.header}><View><Text style={s.eyebrow}>HANJI SETTINGS</Text><Text style={s.title}>필기 환경</Text></View><Pressable accessibilityLabel="설정 닫기" onPress={onClose} style={s.close}><Ionicons name="close" size={23} color={C.ink}/></Pressable></View><ScrollView contentContainerStyle={s.body}><Text style={s.section}>입력과 배치</Text><SettingRow label="손가락으로 필기" help="끄면 손가락은 스크롤과 확대에만 사용합니다." value={value.fingerDrawingEnabled} onChange={toggle('fingerDrawingEnabled')}/><SettingRow label="왼손 모드" help="페이지 레일과 떠 있는 컨트롤을 오른쪽으로 옮깁니다." value={value.leftHanded} onChange={toggle('leftHanded')}/><SettingRow label="다크 페이퍼 잉크 자동 반전" help="검정 잉크는 밝게, 다크 페이퍼를 떠날 때는 다시 검정으로 바꿉니다." value={value.autoDarkInk} onChange={toggle('autoDarkInk')}/><Text style={s.section}>새 페이지 기본 템플릿</Text><View style={s.templates}>{templates.map(item=><Pressable key={item.value} accessibilityLabel={`${item.label} 기본 템플릿`} accessibilityState={{selected:value.defaultTemplate===item.value}} onPress={()=>onChange({...value,defaultTemplate:item.value})} style={[s.template,value.defaultTemplate===item.value&&s.selected]}><View style={[s.paper,item.value==='dark'&&s.dark]}>{item.value==='line'&&<View style={s.line}/>}<Text style={[s.templateCode,item.value==='dark'&&{color:'#F4F1E8'}]}>{item.label.slice(0,1)}</Text></View><Text style={[s.templateLabel,value.defaultTemplate===item.value&&{color:C.accent}]}>{item.label}</Text></Pressable>)}</View><Text style={s.note}>설정은 이 iPad에 저장됩니다. 기본 템플릿은 새 노트와 새 페이지부터 적용되고 기존 페이지는 바뀌지 않습니다.</Text></ScrollView></View></Modal>;
}
function SettingRow({label,help,value,onChange}:{label:string;help:string;value:boolean;onChange:(value:boolean)=>void}){return <View style={s.row}><View style={{flex:1}}><Text style={s.label}>{label}</Text><Text style={s.help}>{help}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{true:C.accentSoft}} thumbColor={value?C.accent:undefined}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#F8F7F2'},header:{height:76,paddingHorizontal:22,borderBottomWidth:1,borderBottomColor:C.line,backgroundColor:C.white,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:C.accent},title:{fontSize:23,fontWeight:'800',color:C.ink,marginTop:3},close:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:C.accentSoft},body:{padding:22,gap:12},section:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:C.accent,marginTop:8},row:{minHeight:72,padding:15,borderRadius:16,borderWidth:1,borderColor:C.line,backgroundColor:C.white,flexDirection:'row',alignItems:'center',gap:15},label:{fontSize:14,fontWeight:'800',color:C.ink},help:{fontSize:11,lineHeight:16,color:C.muted,marginTop:4},templates:{flexDirection:'row',flexWrap:'wrap',gap:10},template:{width:76,padding:8,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:C.white,alignItems:'center'},selected:{borderColor:C.accent,backgroundColor:C.accentSoft},paper:{width:48,height:34,borderRadius:5,borderWidth:1,borderColor:C.line,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',overflow:'hidden'},dark:{backgroundColor:'#202522'},line:{position:'absolute',left:0,right:0,top:16,height:1,backgroundColor:'#DDE2DD'},templateCode:{fontSize:10,fontWeight:'900',color:C.muted},templateLabel:{fontSize:10,fontWeight:'700',color:C.muted,marginTop:6},note:{fontSize:11,lineHeight:17,color:C.muted,marginTop:8}});
