import {Ionicons} from '@expo/vector-icons';
import {FlatList,Image,Modal,Pressable,StyleSheet,Text,View} from 'react-native';
import {C} from '../theme';
import type {Sticker} from '../types';

export function StickerPanel({visible,stickers,onClose,onInsert,onImport,onDelete}:{visible:boolean;stickers:Sticker[];onClose:()=>void;onInsert:(sticker:Sticker)=>void;onImport:()=>void;onDelete:(id:string)=>void}){
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={s.scrim} onPress={onClose}><Pressable style={s.card} onPress={()=>undefined}><View style={s.header}><View><Text style={s.eyebrow}>나의 컬렉션</Text><Text style={s.title}>스티커와 클리핑</Text></View><View style={s.actions}><Pressable accessibilityLabel="이미지를 스티커로 가져오기" onPress={onImport} style={s.import}><Ionicons name="add" size={17} color="white"/><Text style={s.importText}>가져오기</Text></Pressable><Pressable accessibilityLabel="닫기" onPress={onClose} style={s.close}><Ionicons name="close" size={21} color={C.ink}/></Pressable></View></View><Text style={s.help}>이미지를 한 번 보관하면 다른 노트와 페이지에서도 원본 파일 복제 없이 다시 사용할 수 있습니다.</Text>{stickers.length===0?<View style={s.empty}><Ionicons name="images-outline" size={36} color={C.line}/><Text style={s.emptyText}>이미지를 가져오거나 페이지의 이미지 편집 메뉴에서 보관해 주세요.</Text></View>:<FlatList data={stickers} numColumns={4} keyExtractor={item=>item.id} contentContainerStyle={s.grid} renderItem={({item})=><View style={s.item}><Pressable accessibilityLabel={`${item.name} 삽입`} onPress={()=>onInsert(item)} style={s.preview}><Image source={{uri:item.uri}} resizeMode={item.fit??'contain'} style={[StyleSheet.absoluteFill,{transform:[{rotate:`${item.rotation??0}deg`}]}]}/></Pressable><View style={s.itemBottom}><Text numberOfLines={1} style={s.name}>{item.name}</Text><Pressable accessibilityLabel={`${item.name} 삭제`} onPress={()=>onDelete(item.id)}><Ionicons name="trash-outline" size={15} color={C.danger}/></Pressable></View></View>}/>}</Pressable></Pressable></Modal>;
}
const s=StyleSheet.create({scrim:{flex:1,backgroundColor:'rgba(24,27,25,.32)',alignItems:'center',justifyContent:'center',padding:24},card:{width:'78%',maxWidth:760,maxHeight:'76%',minHeight:360,backgroundColor:C.white,borderRadius:22,padding:20,shadowColor:'#000',shadowOpacity:.2,shadowRadius:24},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1,color:C.accent},title:{fontSize:23,fontWeight:'800',color:C.ink,marginTop:3},actions:{flexDirection:'row',gap:8,alignItems:'center'},import:{height:36,paddingHorizontal:12,borderRadius:10,backgroundColor:C.accent,flexDirection:'row',alignItems:'center',gap:5},importText:{color:'white',fontWeight:'800',fontSize:12},close:{width:36,height:36,borderRadius:10,backgroundColor:C.accentSoft,alignItems:'center',justifyContent:'center'},help:{fontSize:12,color:C.muted,marginTop:12,marginBottom:12},grid:{gap:12,paddingBottom:12},item:{width:'24%',marginRight:'1%',marginBottom:13},preview:{aspectRatio:1,backgroundColor:'#F4F3EF',borderRadius:13,overflow:'hidden',borderWidth:1,borderColor:C.line},itemBottom:{flexDirection:'row',alignItems:'center',gap:4,marginTop:6},name:{fontSize:10,color:C.ink,flex:1},empty:{flex:1,minHeight:220,alignItems:'center',justifyContent:'center',gap:10},emptyText:{maxWidth:330,textAlign:'center',fontSize:12,color:C.muted}});
