import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import {useEffect,useState} from 'react';
import type { ToolKind, ToolSpec } from '../types';
import { C } from '../theme';
import {defaultToolPresets,isInkTool,loadToolPreferences,rememberInkTool,saveToolPreferences,selectToolKind,type ToolPreferences} from '../toolPreferences';
import {pickColor} from '../colorPicker';
import {stepBrushOpacity,stepBrushWidth} from '../brushControls';

const tools: { kind: ToolKind; icon: keyof typeof Ionicons.glyphMap; label: string }[] = [
  { kind: 'pen', icon: 'pencil', label: '볼펜' },
  { kind: 'fountainPen', icon: 'create-outline', label: '만년필' },
  { kind: 'monoline', icon: 'remove-outline', label: '모노라인' },
  { kind: 'pencil', icon: 'pencil-outline', label: '연필' },
  { kind: 'crayon', icon: 'color-palette-outline', label: '크레용' },
  { kind: 'watercolor', icon: 'water-outline', label: '수채화' },
  { kind: 'marker', icon: 'brush', label: '형광펜' },
  { kind: 'eraser', icon: 'backspace-outline', label: '지우개' },
  { kind: 'lasso', icon: 'scan-outline', label: '라쏘' },
  { kind: 'shape', icon: 'shapes-outline', label: '도형' },
];
const colors = ['#20201E', '#225D50', '#315E9C', '#A4493D', '#8A653E'];
const eraserLabels = {vector:'획',bitmap:'픽셀',fixedWidthBitmap:'고정'} as const;
const shapeLabels = {line:'선',arrow:'화살표',ellipse:'원',rectangle:'사각',triangle:'삼각'} as const;

export function Toolbar({ tool, setTool, onLibrary, title, onTitleChange, onAddPage, onUndo, onRedo, fingerDrawingEnabled, onToggleFingerDrawing, zoomWindowEnabled, onToggleZoomWindow, viewMode, onToggleViewMode, elementMode, onAddText, onAddImage, onStickers, privacyEnabled, onPrivacyToggle, focusMode,focusOverlay,onActivity,onFocusMode, onSettings,onSearch, onExportPdf, onFlashcards, dueCards, onPdfOutline, outlineCount }: { tool: ToolSpec; setTool: (v: ToolSpec) => void; onLibrary: () => void; title: string; onTitleChange: (v: string) => void; onAddPage: () => void; onUndo:()=>void; onRedo:()=>void; fingerDrawingEnabled:boolean; onToggleFingerDrawing:()=>void;zoomWindowEnabled:boolean;onToggleZoomWindow:()=>void;viewMode:'page'|'continuous';onToggleViewMode:()=>void;elementMode:boolean;onAddText:()=>void;onAddImage:()=>void;onStickers:()=>void;privacyEnabled:boolean;onPrivacyToggle:()=>void;focusMode?:boolean;focusOverlay?:boolean;onActivity?:()=>void;onFocusMode:()=>void;onSettings:()=>void;onSearch:()=>void; onExportPdf:()=>void;onFlashcards:()=>void;dueCards:number;onPdfOutline?:()=>void;outlineCount:number }) {
  const [preferences,setPreferences]=useState<ToolPreferences>({presets:defaultToolPresets,recentColors:[],lastTools:{}});
  const {width}=useWindowDimensions();const compact=width<760;
  useEffect(()=>{void loadToolPreferences().then(setPreferences)},[]);
  const persist=(next:ToolPreferences)=>{setPreferences(next);void saveToolPreferences(next)};
  const applyTool=(next:ToolSpec)=>{setTool(next);if(isInkTool(next.kind))persist(rememberInkTool(preferences,next))};
  const chooseColor=(color:string)=>{const next={...tool,color};setTool(next);const recent=[color,...preferences.recentColors.filter(x=>x.toUpperCase()!==color.toUpperCase())].slice(0,8);persist({...rememberInkTool(preferences,next),recentColors:recent})};
  const openColorPicker=async()=>{const color=await pickColor(tool.color);if(/^#[0-9A-F]{6}$/i.test(color))chooseColor(color)};
  const savePreset=(index:number)=>{if(!isInkTool(tool.kind))return;const presets=[...preferences.presets];const preset=presets[index];if(!preset)return;presets[index]={...preset,tool:{...tool}};persist({...preferences,presets})};
  const addPreset=()=>{if(!isInkTool(tool.kind)||preferences.presets.length>=12)return;persist({...preferences,presets:[...preferences.presets,{id:`preset-${Date.now()}`,name:`프리셋 ${preferences.presets.length+1}`,tool:{...tool}}]})};
  return <View style={[s.bar,focusOverlay&&s.overlay]} onTouchStart={onActivity}>
    <Pressable accessibilityLabel="서재" onPress={onLibrary} style={s.nav}><Ionicons name="library-outline" size={20} color={C.ink} />{!compact&&<Text style={s.navText}>서재</Text>}</Pressable>
    {!compact&&<><TextInput value={title} onChangeText={onTitleChange} selectTextOnFocus style={s.title} accessibilityLabel="노트 제목" /><View style={s.rule} /></>}
    <ScrollView horizontal style={s.toolScroll} contentContainerStyle={s.tools} showsHorizontalScrollIndicator={false}>
      <View style={s.presets}>{preferences.presets.map((preset,index)=><Pressable key={preset.id} accessibilityLabel={`${preset.name}, 길게 눌러 현재 도구 저장`} onPress={()=>applyTool({...preset.tool})} onLongPress={()=>savePreset(index)} delayLongPress={450} style={[s.preset,tool.kind===preset.tool.kind&&tool.color.toUpperCase()===preset.tool.color.toUpperCase()&&tool.width===preset.tool.width&&s.presetActive]}><View style={[s.presetNib,{backgroundColor:preset.tool.color,width:Math.min(17,Math.max(5,preset.tool.width+4)),height:Math.min(17,Math.max(5,preset.tool.width+4)),opacity:preset.tool.opacity??1}]}/></Pressable>)}<Pressable accessibilityLabel="현재 도구 프리셋 추가" disabled={!isInkTool(tool.kind)||preferences.presets.length>=12} onPress={addPreset} style={[s.preset,(!isInkTool(tool.kind)||preferences.presets.length>=12)&&s.disabled]}><Ionicons name="add" size={15} color={C.accent}/></Pressable></View>
      <View style={s.rule}/>
      {tools.map(x => <Pressable accessibilityLabel={x.label} key={x.kind} onPress={() => applyTool(selectToolKind(tool,x.kind,preferences.lastTools))} style={[s.tool, tool.kind === x.kind && s.selected]}><Ionicons name={x.icon} size={21} color={tool.kind === x.kind ? C.accent : C.muted} /></Pressable>)}
      <Pressable accessibilityLabel="자" onPress={()=>applyTool({...tool,rulerActive:!tool.rulerActive})} style={[s.tool,tool.rulerActive&&s.selected]}><Ionicons name="resize-outline" size={21} color={tool.rulerActive?C.accent:C.muted}/></Pressable>
      <Pressable accessibilityLabel="긁어서 지우기" onPress={()=>applyTool({...tool,scratchEnabled:!(tool.scratchEnabled??true)})} style={[s.tool,(tool.scratchEnabled??true)&&s.selected]}><Ionicons name="remove-circle-outline" size={21} color={(tool.scratchEnabled??true)?C.accent:C.muted}/></Pressable>
      <Pressable accessibilityLabel="원 그려 올가미" accessibilityState={{selected:tool.circleToLasso??true}} onPress={()=>applyTool({...tool,circleToLasso:!(tool.circleToLasso??true)})} style={[s.tool,(tool.circleToLasso??true)&&s.selected]}><Ionicons name="ellipse-outline" size={21} color={(tool.circleToLasso??true)?C.accent:C.muted}/></Pressable>
      {tool.kind==='eraser'&&<View style={s.segment}>{(Object.keys(eraserLabels) as (keyof typeof eraserLabels)[]).map(mode=><Pressable key={mode} onPress={()=>setTool({...tool,eraserMode:mode})} style={[s.segmentButton,(tool.eraserMode??'vector')===mode&&s.segmentActive]}><Text style={s.segmentText}>{eraserLabels[mode]}</Text></Pressable>)}<Pressable accessibilityLabel="지우개 사용 후 이전 펜 자동 복귀" onPress={()=>setTool({...tool,eraserAutoReturn:!(tool.eraserAutoReturn??true)})} style={[s.segmentButton,(tool.eraserAutoReturn??true)&&s.segmentActive]}><Text style={s.segmentText}>자동↩</Text></Pressable></View>}
      {tool.kind==='marker'&&<Pressable accessibilityLabel="형광펜 그리고 홀드 직선 고정" accessibilityState={{selected:tool.markerStraightLine??true}} onPress={()=>applyTool({...tool,markerStraightLine:!(tool.markerStraightLine??true)})} style={[s.segmentButton,s.markerStraight,(tool.markerStraightLine??true)&&s.segmentActive]}><Ionicons name="remove-outline" size={15} color={(tool.markerStraightLine??true)?C.accent:C.muted}/><Text style={s.segmentText}>홀드 직선</Text></Pressable>}
      {tool.kind==='shape'&&<><View style={s.segment}>{(Object.keys(shapeLabels) as (keyof typeof shapeLabels)[]).map(shapeKind=><Pressable key={shapeKind} onPress={()=>setTool({...tool,shapeKind})} style={[s.segmentButton,(tool.shapeKind??'line')===shapeKind&&s.segmentActive]}><Text style={s.segmentText}>{shapeLabels[shapeKind]}</Text></Pressable>)}</View><View style={s.segment}>{(['solid','dashed'] as const).map(style=><Pressable accessibilityLabel={style==='solid'?'도형 실선':'도형 점선'} key={style} onPress={()=>setTool({...tool,shapeLineStyle:style})} style={[s.segmentButton,(tool.shapeLineStyle??'solid')===style&&s.segmentActive]}><Text style={s.segmentText}>{style==='solid'?'실선':'점선'}</Text></Pressable>)}</View><Pressable accessibilityLabel="도형 스냅에 끝점 홀드 필요" accessibilityState={{selected:tool.shapeHoldRequired??true}} onPress={()=>setTool({...tool,shapeHoldRequired:!(tool.shapeHoldRequired??true)})} style={[s.segmentButton,s.markerStraight,(tool.shapeHoldRequired??true)&&s.segmentActive]}><Ionicons name="timer-outline" size={14} color={(tool.shapeHoldRequired??true)?C.accent:C.muted}/><Text style={s.segmentText}>홀드 필요</Text></Pressable></>}
      <View style={s.colors}>{[...colors,...preferences.recentColors.filter(x=>!colors.includes(x))].slice(0,8).map(color => <Pressable accessibilityLabel={`색상 ${color}`} key={color} onPress={() => chooseColor(color)} style={[s.color, { backgroundColor: color }, tool.color.toUpperCase() === color.toUpperCase() && s.colorSelected]} />)}</View>
      <Pressable accessibilityLabel="시스템 컬러 피커와 스포이드" onPress={()=>void openColorPicker()} style={s.colorPicker}><Ionicons name="eyedrop-outline" size={18} color={C.accent}/></Pressable>
      <TextInput accessibilityLabel="HEX 색상" value={tool.color} autoCapitalize="characters" maxLength={7} onChangeText={color=>{if(/^#[0-9A-Fa-f]{0,6}$/.test(color)){setTool({...tool,color});if(/^#[0-9A-Fa-f]{6}$/.test(color))chooseColor(color)}}} style={s.hex} />
      <View style={s.fineControl}><Pressable accessibilityLabel="브러시 굵기 줄이기" onPress={()=>applyTool({...tool,width:stepBrushWidth(tool.width,-1)})} style={s.fineButton}><Ionicons name="remove" size={14} color={C.accent}/></Pressable><Text style={s.fineValue}>{tool.width.toFixed(1)}pt</Text><Pressable accessibilityLabel="브러시 굵기 늘리기" onPress={()=>applyTool({...tool,width:stepBrushWidth(tool.width,1)})} style={s.fineButton}><Ionicons name="add" size={14} color={C.accent}/></Pressable></View>
      <View style={s.fineControl}><Pressable accessibilityLabel="브러시 불투명도 줄이기" onPress={()=>applyTool({...tool,opacity:stepBrushOpacity(tool.opacity??1,-1)})} style={s.fineButton}><Ionicons name="remove" size={14} color={C.accent}/></Pressable><Text style={s.fineValue}>{Math.round((tool.opacity??1)*100)}%</Text><Pressable accessibilityLabel="브러시 불투명도 늘리기" onPress={()=>applyTool({...tool,opacity:stepBrushOpacity(tool.opacity??1,1)})} style={s.fineButton}><Ionicons name="add" size={14} color={C.accent}/></Pressable></View>
    </ScrollView>
    <ScrollView horizontal style={[s.trailingScroll,compact&&s.trailingCompact]} contentContainerStyle={s.trailing} showsHorizontalScrollIndicator={false}>
    {compact&&<TextInput value={title} onChangeText={onTitleChange} selectTextOnFocus style={[s.title,s.compactTitle]} accessibilityLabel="노트 제목"/>}
    <Pressable accessibilityLabel="플래시카드" onPress={onFlashcards} style={s.tool}><Ionicons name="albums-outline" size={20} color={C.accent}/>{dueCards>0&&<View style={s.badge}><Text style={s.badgeText}>{Math.min(99,dueCards)}</Text></View>}</Pressable>
    <Pressable accessibilityLabel="현재 문서 안 검색" onPress={onSearch} style={s.tool}><Ionicons name="search-outline" size={20} color={C.accent}/></Pressable>
    {onPdfOutline&&<Pressable accessibilityLabel={`PDF 목차 ${outlineCount}개`} disabled={!outlineCount} onPress={onPdfOutline} style={[s.tool,!outlineCount&&{opacity:.35}]}><Ionicons name="list-outline" size={20} color={C.accent}/></Pressable>}
    <Pressable accessibilityLabel="PDF PNG 원본 내보내기" onPress={onExportPdf} style={s.tool}><Ionicons name="share-outline" size={20} color={C.accent}/></Pressable>
    <Pressable accessibilityLabel="실행 취소" onPress={onUndo} style={s.tool}><Ionicons name="arrow-undo" size={20} color={C.muted}/></Pressable>
    <Pressable accessibilityLabel="다시 실행" onPress={onRedo} style={s.tool}><Ionicons name="arrow-redo" size={20} color={C.muted}/></Pressable>
    <Pressable accessibilityLabel="손가락 필기" onPress={onToggleFingerDrawing} style={[s.tool,fingerDrawingEnabled&&s.selected]}><Ionicons name="hand-left-outline" size={20} color={fingerDrawingEnabled?C.accent:C.muted}/></Pressable>
    <Pressable accessibilityLabel={viewMode==='continuous'?'페이지 넘김 모드':'세로 연속 스크롤 모드'} onPress={onToggleViewMode} style={[s.tool,viewMode==='continuous'&&s.selected]}><Ionicons name={viewMode==='continuous'?'reader-outline':'swap-vertical-outline'} size={21} color={viewMode==='continuous'?C.accent:C.muted}/></Pressable>
    <Pressable accessibilityLabel="확대 필기창 자동 전진" onPress={onToggleZoomWindow} style={[s.tool,zoomWindowEnabled&&s.selected]}><Ionicons name="scan-circle-outline" size={21} color={zoomWindowEnabled?C.accent:C.muted}/></Pressable>
    <Pressable accessibilityLabel="텍스트 상자 추가" onPress={onAddText} style={[s.tool,elementMode&&s.selected]}><Ionicons name="text-outline" size={21} color={elementMode?C.accent:C.muted}/></Pressable>
    <Pressable accessibilityLabel="이미지 삽입" onPress={onAddImage} style={s.tool}><Ionicons name="image-outline" size={21} color={C.accent}/></Pressable>
    <Pressable accessibilityLabel="스티커 컬렉션" onPress={onStickers} style={s.tool}><Ionicons name="file-tray-stacked-outline" size={21} color={C.accent}/></Pressable>
    <Pressable accessibilityLabel={privacyEnabled?'노트 잠금 끄기':'노트 잠금 켜기'} onPress={onPrivacyToggle} style={[s.tool,privacyEnabled&&s.selected]}><Ionicons name={privacyEnabled?'lock-closed':'lock-open-outline'} size={19} color={privacyEnabled?C.accent:C.muted}/></Pressable>
    <Pressable accessibilityLabel="필기 환경 설정" onPress={onSettings} style={s.tool}><Ionicons name="settings-outline" size={20} color={C.muted}/></Pressable>
    <Pressable accessibilityLabel={focusMode?'집중 모드 종료':'집중 모드'} onPress={onFocusMode} style={[s.tool,focusMode&&s.selected]}><Ionicons name={focusMode?'contract-outline':'expand-outline'} size={20} color={focusMode?C.accent:C.muted}/></Pressable>
    <Pressable accessibilityLabel="페이지 추가" onPress={onAddPage} style={s.add}><Ionicons name="add" size={20} color="white" />{!compact&&<Text style={s.addText}>페이지</Text>}</Pressable>
    </ScrollView>
  </View>;
}

const s = StyleSheet.create({
  bar: { height: 64, backgroundColor: C.white, borderBottomWidth: 1, borderBottomColor: C.line, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 10 },overlay:{position:'absolute',top:0,left:0,right:0,zIndex:50,shadowColor:'#000',shadowOpacity:.12,shadowRadius:10,shadowOffset:{width:0,height:5}},
  nav: { flexDirection: 'row', alignItems: 'center', gap: 7, padding: 8 }, navText: { fontSize: 14, fontWeight: '600', color: C.ink }, title: { maxWidth: 160, fontWeight: '700', color: C.ink },compactTitle:{width:112,height:38,borderWidth:1,borderColor:C.line,borderRadius:10,paddingHorizontal:9},
  rule: { height: 28, width: 1, backgroundColor: C.line },toolScroll:{flex:1,minWidth:70}, tools: { alignItems: 'center', gap: 6 },trailingScroll:{flexShrink:0,width:430},trailingCompact:{width:124},trailing:{alignItems:'center',gap:5,paddingHorizontal:2}, tool: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, selected: { backgroundColor: C.accentSoft },
  presets:{flexDirection:'row',gap:5,alignItems:'center'},preset:{width:30,height:34,borderRadius:10,borderWidth:1,borderColor:C.line,backgroundColor:C.white,alignItems:'center',justifyContent:'center'},presetActive:{borderColor:C.accent,backgroundColor:C.accentSoft},presetNib:{borderRadius:20},disabled:{opacity:.3},
  segment:{height:34,flexDirection:'row',borderWidth:1,borderColor:C.line,borderRadius:9,overflow:'hidden'},segmentButton:{paddingHorizontal:8,alignItems:'center',justifyContent:'center'},segmentActive:{backgroundColor:C.accentSoft},segmentText:{fontSize:10,fontWeight:'700',color:C.muted},markerStraight:{height:34,borderWidth:1,borderColor:C.line,borderRadius:9,flexDirection:'row',gap:3},
  colors: { flexDirection: 'row', gap: 7, paddingHorizontal: 8 }, color: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: C.white }, colorSelected: { outlineWidth: 2, outlineColor: C.accent, outlineOffset: 2 } as never,
  hex:{height:32,width:72,borderWidth:1,borderColor:C.line,borderRadius:8,paddingHorizontal:7,fontSize:11,color:C.ink},colorPicker:{width:32,height:32,borderRadius:9,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},opacity:{height:30,minWidth:31,borderRadius:8,alignItems:'center',justifyContent:'center',paddingHorizontal:3},opacityText:{fontSize:9,color:C.muted,fontWeight:'700'}, width: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },badge:{position:'absolute',right:0,top:0,minWidth:16,height:16,borderRadius:8,backgroundColor:C.danger,alignItems:'center',justifyContent:'center',paddingHorizontal:3},badgeText:{fontSize:9,fontWeight:'800',color:C.white}, add: { flexDirection: 'row', alignItems: 'center', justifyContent:'center', backgroundColor: C.accent, borderRadius: 12, paddingHorizontal: 12, height: 38, minWidth:40, gap: 4 }, addText: { color: 'white', fontWeight: '700' },
  fineControl:{height:34,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:C.line,borderRadius:9,overflow:'hidden'},fineButton:{width:28,height:34,alignItems:'center',justifyContent:'center',backgroundColor:C.accentSoft},fineValue:{minWidth:43,textAlign:'center',fontSize:10,fontWeight:'800',color:C.ink},
});
