import {Ionicons} from '@expo/vector-icons';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {C} from '../theme';
import type {AudioSession} from '../types';

const clock=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds)%60).padStart(2,'0')}`;
export function TranscriptPanel({visible,session,currentTime,onClose,onSeek}:{visible:boolean;session:AudioSession;currentTime:number;onClose:()=>void;onSeek:(seconds:number)=>void}){
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.scrim}><View style={s.card}><View style={s.header}><View><Text style={s.eyebrow}>온디바이스 전사</Text><Text style={s.title}>탭해서 해당 시점 듣기</Text></View><Pressable accessibilityLabel="전사문 닫기" onPress={onClose} style={s.close}><Ionicons name="close" size={21} color={C.ink}/></Pressable></View><ScrollView contentContainerStyle={s.body}>{(session.transcriptSegments??[]).length?<View style={s.words}>{session.transcriptSegments!.map((segment,index)=>{const active=currentTime>=segment.start&&currentTime<segment.start+Math.max(segment.duration,.35);return <Pressable key={`${segment.start}-${index}`} accessibilityLabel={`${clock(segment.start)} ${segment.text}`} onPress={()=>onSeek(segment.start)} style={[s.word,active&&s.active]}><Text style={[s.wordText,active&&s.activeText]}>{segment.text}</Text><Text style={[s.time,active&&s.activeText]}>{clock(segment.start)}</Text></Pressable>})}</View>:<Text style={s.paragraph}>{session.transcript}</Text>}</ScrollView></View></View></Modal>;
}
const s=StyleSheet.create({scrim:{flex:1,backgroundColor:'rgba(20,24,22,.35)',alignItems:'center',justifyContent:'center',padding:24},card:{width:'72%',maxWidth:760,height:'70%',backgroundColor:C.white,borderRadius:22,padding:20},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1,color:C.accent},title:{fontSize:21,fontWeight:'800',color:C.ink,marginTop:3},close:{width:38,height:38,borderRadius:11,backgroundColor:C.accentSoft,alignItems:'center',justifyContent:'center'},body:{paddingBottom:24},words:{flexDirection:'row',flexWrap:'wrap',gap:7},word:{borderRadius:9,borderWidth:1,borderColor:C.line,backgroundColor:'#FAFAF7',paddingHorizontal:9,paddingVertical:7},active:{backgroundColor:C.accent,borderColor:C.accent},wordText:{fontSize:14,fontWeight:'600',color:C.ink},time:{fontSize:8,color:C.muted,marginTop:3},activeText:{color:C.white},paragraph:{fontSize:15,lineHeight:25,color:C.ink}});
