import assert from 'node:assert/strict';
import {SHAPE_HOLD_MS,nearestShapeAnchor,shapeEndpointSnapDistance,shouldSnapShape} from '../src/shapePolicy.ts';
assert.equal(SHAPE_HOLD_MS,350);
assert.equal(shouldSnapShape(true,true),true);
assert.equal(shouldSnapShape(true,false),false);
assert.equal(shouldSnapShape(false,false),true);
assert.equal(shouldSnapShape(false,true),true);
assert.equal(shapeEndpointSnapDistance(1),12);
assert.equal(shapeEndpointSnapDistance(4),16);
assert.equal(shapeEndpointSnapDistance(20),24);
assert.deepEqual(nearestShapeAnchor({x:10,y:10},[{x:30,y:30},{x:14,y:12}],12),{x:14,y:12});
assert.equal(nearestShapeAnchor({x:10,y:10},[{x:30,y:30}],12),undefined);
console.log('shape hold policy verification passed');
