import type {Notebook,Page} from './types';

const assetIdentity=(uri?:string)=>{if(!uri)return undefined;try{return decodeURIComponent(uri.split('/').pop()??'').replace(/^\d+-/,'')}catch{return uri.split('/').pop()}};
const pageContent=(page:Page)=>({id:page.id,drawingData:page.drawingData,template:page.template,rotation:page.rotation,customTemplate:assetIdentity(page.customTemplateUri),bookmarked:page.bookmarked,elements:(page.elements??[]).map(element=>element.kind==='image'?{...element,uri:assetIdentity(element.uri)}:element),pdfName:page.pdfName,pdfPageIndex:page.pdfPageIndex});
const noteContent=(note:Notebook)=>JSON.stringify({title:note.title,folder:note.folder,tags:note.tags,favorite:note.favorite,viewMode:note.viewMode,pages:note.pages.map(pageContent),audio:(note.audioSessions??[]).map(session=>({asset:assetIdentity(session.uri),createdAt:session.createdAt,startedAt:session.startedAt,durationMs:session.durationMs,strokes:session.strokes})),flashcards:note.flashcards});
const signature=(value:string)=>{let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,'0')};
const cloneConflict=(note:Notebook,sourceId:string,stamp:string):Notebook=>{const pageIds=new Map(note.pages.map(page=>[page.id,`${page.id}-conflict-${stamp}`]));return{...note,id:`${sourceId}-conflict-${stamp}`,title:`${note.title} (충돌 사본)`,favorite:false,updatedAt:new Date().toISOString(),conflictOf:sourceId,conflictSignature:signature(noteContent(note)),pages:note.pages.map(page=>({...page,id:pageIds.get(page.id)!})),audioSessions:note.audioSessions?.map(session=>({...session,strokes:session.strokes.map(stroke=>({...stroke,pageId:pageIds.get(stroke.pageId)??stroke.pageId}))}))}};

export function mergeCloudRestore(local:Notebook[],remote:Notebook[]):Notebook[]{
 const merged=new Map(local.map(note=>[note.id,note]));const conflicts=[...local.filter(note=>note.conflictSignature)];
 for(const incoming of remote){const current=merged.get(incoming.id);if(!current){merged.set(incoming.id,incoming);continue}const localContent=noteContent(current),remoteContent=noteContent(incoming);if(localContent===remoteContent){if(incoming.updatedAt>current.updatedAt)merged.set(incoming.id,incoming);continue}const remoteWins=incoming.updatedAt>current.updatedAt,winner=remoteWins?incoming:current,loser=remoteWins?current:incoming,loserSignature=signature(noteContent(loser));merged.set(incoming.id,winner);if(!conflicts.some(note=>note.conflictOf===incoming.id&&note.conflictSignature===loserSignature)){const copy=cloneConflict(loser,incoming.id,`${Date.now()}-${loserSignature}`);conflicts.push(copy);merged.set(copy.id,copy)}}
 return [...merged.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
}
