import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type {Notebook,Page} from './types';
type Stroke={d:string;color:string;width:number;opacity:number};
const esc=(v:string)=>v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
export async function exportNotebookPdf(note:Notebook){
 const pages=note.pages.map(page=>{let strokes:Stroke[]=[];try{strokes=JSON.parse(page.drawingData||'[]')}catch{}const paths=strokes.map(x=>`<path d="${esc(x.d)}" stroke="${esc(x.color)}" stroke-width="${x.width}" opacity="${x.opacity}" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`).join('');return `<section class="page ${page.template}"><svg viewBox="0 0 900 636">${paths}</svg></section>`}).join('');
 const html=`<!doctype html><html><head><style>@page{size:A4 landscape;margin:0}body{margin:0}.page{width:297mm;height:210mm;page-break-after:always;background:#fff}.line{background-image:repeating-linear-gradient(#fff 0,#fff 27px,#dde2dd 28px)}.grid{background-image:linear-gradient(#dde2dd 1px,transparent 1px),linear-gradient(90deg,#dde2dd 1px,transparent 1px);background-size:28px 28px}.dot{background-image:radial-gradient(#bdc4bd 1px,transparent 1px);background-size:22px 22px}.cornell{background-image:linear-gradient(90deg,transparent 24.8%,#bfd0c8 25%,transparent 25.2%),linear-gradient(0deg,transparent 17.8%,#bfd0c8 18%,transparent 18.2%),repeating-linear-gradient(#fff 0,#fff 27px,#dde2dd 28px)}.planner{background-image:linear-gradient(#dde2dd 1px,transparent 1px),linear-gradient(90deg,#dde2dd 1px,transparent 1px);background-size:100% 11.11%,14.285% 100%}.dark{background-color:#202522;background-image:repeating-linear-gradient(transparent 0,transparent 27px,#465149 28px)}svg{width:100%;height:100%}</style></head><body>${pages}</body></html>`;
 const {uri}=await Print.printToFileAsync({html});await Sharing.shareAsync(uri,{mimeType:'application/pdf',dialogTitle:`${note.title} PDF 내보내기`});return uri;
}
export async function exportPagePng(note:Notebook,page:Page,pageIndex:number){
 let strokes:Stroke[]=[];try{strokes=JSON.parse(page.drawingData||'[]')}catch{}
 const paths=strokes.map(x=>`<path d="${esc(x.d)}" stroke="${esc(x.color)}" stroke-width="${x.width}" opacity="${x.opacity}" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`).join('');
 const ruled='<defs><pattern id="r" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M0 27.5H28" stroke="#dde2dd"/></pattern><pattern id="g" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M0 27.5H28M27.5 0V28" stroke="#dde2dd"/></pattern><pattern id="d" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#bdc4bd"/></pattern></defs>';
 const background=page.template==='dark'?'<rect width="900" height="636" fill="#202522"/><path d="M0 28H900M0 56H900M0 84H900M0 112H900M0 140H900M0 168H900M0 196H900M0 224H900M0 252H900M0 280H900M0 308H900M0 336H900M0 364H900M0 392H900M0 420H900M0 448H900M0 476H900M0 504H900M0 532H900M0 560H900M0 588H900M0 616H900" stroke="#465149"/>':page.template==='cornell'?`${ruled}<rect width="900" height="636" fill="white"/><rect x="225" width="675" height="521" fill="url(#r)"/><path d="M225 0V521M0 521H900" stroke="#bfd0c8"/>`:page.template==='planner'?`<rect width="900" height="636" fill="white"/><path d="${Array.from({length:8},(_,i)=>`M${i*128.57} 60V620`).join(' ')} ${Array.from({length:10},(_,i)=>`M0 ${60+i*62}H900`).join(' ')}" stroke="#dde2dd"/>`:page.template==='line'?`${ruled}<rect width="900" height="636" fill="url(#r)"/>`:page.template==='grid'?`${ruled}<rect width="900" height="636" fill="url(#g)"/>`:page.template==='dot'?`${ruled}<rect width="900" height="636" fill="url(#d)"/>`:'<rect width="900" height="636" fill="white"/>';
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="2700" height="1908" viewBox="0 0 900 636">${background}${paths}</svg>`;
 const image=new Image();const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('PNG 렌더링 실패'));image.src=url});
 const canvas=document.createElement('canvas');canvas.width=2700;canvas.height=1908;canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error('PNG 변환 실패')),'image/png'));
 const output=URL.createObjectURL(blob);const link=document.createElement('a');link.href=output;link.download=`${note.title}-${pageIndex+1}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(output),1000);return output;
}
